//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "docs", table_name = "docs_node_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "docs_node_versions_space_id_rel_path_version_key")]
    pub space_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "docs_node_versions_space_id_rel_path_version_key"
    )]
    pub rel_path: String,
    #[sea_orm(unique_key = "docs_node_versions_space_id_rel_path_version_key")]
    pub version: i32,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub content: Option<Json>,
    pub word_count: i32,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
