//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "docs", table_name = "docs_node_attachments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub space_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub rel_path: String,
    #[sea_orm(column_type = "Text")]
    pub storage_key: String,
    #[sea_orm(column_type = "Text")]
    pub file_name: String,
    #[sea_orm(column_type = "Text")]
    pub file_type: String,
    pub file_size: i32,
    pub is_binary: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub detected_mime: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub file_category: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub text_encoding: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub detected_language: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
