//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "doc_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub doc_id: Uuid,
    pub version: i32,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub content: Option<Json>,
    pub word_count: i32,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::docs::Entity",
        from = "Column::DocId",
        to = "super::docs::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Docs,
}

impl Related<super::docs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Docs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
