//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "docs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub app_id: Uuid,
    pub folder_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub content: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub cover_image: Option<String>,
    pub is_favorite: bool,
    pub is_pinned: bool,
    pub is_archived: bool,
    pub word_count: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub search_text: Option<String>,
    pub tags: Option<Vec<String>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::apps::Entity",
        from = "Column::AppId",
        to = "super::apps::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Apps,
    #[sea_orm(has_many = "super::doc_comments::Entity")]
    DocComments,
    #[sea_orm(
        belongs_to = "super::doc_folders::Entity",
        from = "Column::FolderId",
        to = "super::doc_folders::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    DocFolders,
    #[sea_orm(has_many = "super::doc_versions::Entity")]
    DocVersions,
}

impl Related<super::apps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Apps.def()
    }
}

impl Related<super::doc_comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocComments.def()
    }
}

impl Related<super::doc_folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocFolders.def()
    }
}

impl Related<super::doc_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocVersions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
